### PR TITLE
Upgrade Dependencies

### PR DESCRIPTION
**Pull request by CDAGaming**
This PR is a Remake of #6 which Upgrades SDL2, Curl, and QT
(As reported on discord, The update to QT fixes the following error:)
`SetProcessDpiAwareness(2) failed: COM error 0xffffffff80070005  (Unknown error 0x0ffffffff80070005), using 2`

To-Do:

- [x] Test Changes within Local Citra Environment (Tomorrow)

### CODE REVIEW

**Comment by j-selby** [comment]
Why is Curl and SDL being updated, if this is to resolve a Qt bug?

**Comment by CDAGaming** [comment]
QT is both to Solve a Bug and to Add WinExtras for the PR in Citra. As for the Others, They just both have many bug fixes that may or may not be useful to Citra. As for if they were tested for breakage, my Fork of Citra has been using these new Binaries from Day 1 and fortunately hasn't experienced any Issues.

**Comment by wwylele** [comment]
>  They just both have many bug fixes that may or may not be useful to Citra

Please name some of them, and also put them in separate PRs

Here is another thing. Sorry if I am being too skeptical, but how do you prove that these binaries don't contain malicious stuff?

**Comment by zhaowenlan1779** [comment]
This pull request is getting abandoned / inactive for a considerable amount of time. Qt was already updated to 5.10.0 by me, and @FearlessTobi was planning to update SDL2 to 2.0.8 as well. It seemed that the issues mentioned by @j-selby and @wwylele still wasn't solved, so I'm going to close this for now.

Thanks for the contribution!

**Pull request closed without merging**
